version: '3.8'

services:
  backend:
    image: ghcr.io/luca-naujoks/network_overview-backend:latest
    platform: linux/amd64
    ports:
      - "8080:8080"


  frontend:
    image: ghcr.io/luca-naujoks/network_overview-frontend:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - backend
